-- Run these commands in your Supabase SQL Editor

-- 1. Create the new dynamic contexts table
CREATE TABLE IF NOT EXISTS contexts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- Insert default contexts to start with
INSERT INTO contexts (name) VALUES 
  ('Rooxter Films'), 
  ('SaaS/Wunderloom'), 
  ('Family'), 
  ('Podcast') 
ON CONFLICT DO NOTHING;

-- 2. Update the existing tasks table with new columns
ALTER TABLE tasks 
  ADD COLUMN IF NOT EXISTS due_by_type text,      -- Stores "1 hr", "6 hrs", "Today", etc.
  ADD COLUMN IF NOT EXISTS target_deadline timestamptz, -- Exact calculated deadline timestamp
  ADD COLUMN IF NOT EXISTS submitted_on timestamptz DEFAULT now(), -- Exact creation timestamp
  ADD COLUMN IF NOT EXISTS deletion_date timestamptz, -- For 30-day soft delete tracking
  ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false; -- For team member deletion archiving
